Adding Dynamixel/servo ino code and librairy
Ecam-Eurobot-2017/main pull request #12
Opened 2017-02-21 15:20 UTC by antoinevdm

J'ai ajouté le code arduino pour commander les servos (Dynamixel et SG90) via I2C. 
La description du protocole se trouve dans les [https://github.com/Ecam-Eurobot-2017/main/issues/11](issues).

2017-02-22 16:43 UTC, charlesvdv commented
En faisant un peu de recherche, j'ai trouvé le [repo du code pour le Dynamixel](https://sourceforge.net/projects/dynamixelforarduino/files/). Ca permettrait de nous éviter d'ajouter toute la librairie dans le git. Il y a par contre une mini différence entre les fichiers. Il faudrait tester pour voir ce que ca donne 😄

2017-03-18 14:29 UTC, charlesvdv requested changes
Juste quelques petites modifs légères et puis 👍

2017-03-18 14:29 UTC, charlesvdv commented on code/raspberrypi/arduino_servo.py
> +class ArduinoServo(I2C) :
Appeler la classe: ```Kinematics``` ne serait pas plus logique ? 😄

2017-03-18 14:29 UTC, charlesvdv commented on code/raspberrypi/arduino_servo.py
> +    totalling 8 bits together. The 4 first bits are for the serov adress,
```the servo adress```

2017-03-18 14:29 UTC, charlesvdv commented on code/raspberrypi/arduino_servo.py
> +    Dynamixel (ascending and descending the clamp) adress is 1
Les infos sont redondantes avec l'Enum Adress. Pour moi tu peux retirer ces commentaires 😄

2017-03-18 14:29 UTC, charlesvdv commented on code/raspberrypi/arduino_servo.py
> +    def stack_bloc(self) :
c's ```block``` et pas ```bloc```

2017-03-18 14:29 UTC, charlesvdv commented on code/raspberrypi/arduino_servo.py
> +    def release_bloc(self) :
c's ```block``` et pas ```bloc```

2017-03-18 14:29 UTC, charlesvdv commented on code/raspberrypi/arduino_servo.py
> +    MOVE_DOWN = 0
C's bizarre d'avoir ```MOVE_UP``` et  ```MOVE_DOWN``` vu que la majorité des actions font pas un UP ou un DOWN mais d'autres actions. Je sais pas encore trop comment faire pour que ce soit clean :/

2017-03-29 12:18 UTC, JonathanPetit commented
il faut rajouter dans le ```.gitignore``` les extension des fichiers binaires généré par python  ```.pyc``ù et ```__pychache__```.

2017-04-07 07:50 UTC, charlesvdv commented on code/raspberrypi/arduino_servo.py
> +    SERVO_STACK = 3
pas très clair comme nom.

2017-04-07 15:02 UTC, charlesvdv requested changes

2017-04-07 15:02 UTC, charlesvdv commented on code/arduino/kinematics/kinematics.ino
> +//TODO Define other servos and positions
useless

2017-04-07 15:02 UTC, charlesvdv commented on code/arduino/kinematics/kinematics.ino
> +//const int ANGLE_VERTICAL = 205; Depend on the dynamixel's position
useless

2017-04-07 15:02 UTC, charlesvdv commented on code/arduino/kinematics/kinematics.ino
> +//RIGHT VALUE FOR DYNAMIXEL
useless comment

2017-04-07 15:02 UTC, charlesvdv commented on code/arduino/kinematics/kinematics.ino
> +   //Wire.onRequest(sendData);
useless

2017-04-07 15:02 UTC, charlesvdv commented on code/arduino/kinematics/kinematics.ino
> +  //Attache the servo on the PWM pin;
Attach

2017-04-07 15:02 UTC, charlesvdv commented on code/arduino/kinematics/kinematics.ino
> +  //servo_stack.attach(SERVO_STACK_PIN);
useless

2017-04-07 15:02 UTC, charlesvdv commented on code/raspberrypi/kinematics.py
> +
useless lines

2017-04-07 15:06 UTC, charlesvdv approved these changes

2017-04-07 15:07 UTC, merged