[WIP] First design to abstract I2C comm behind a class
Ecam-Eurobot-2017/main pull request #4
Opened 2017-02-01 16:29 UTC by azerupi

Le but est de créer une abstraction autour de la communication I2C pour chaque module. Un module est (généralement) une partie spécifique du robot commandé par une arduino, e.g. les capteurs ultrasons.

2017-02-03 09:00 UTC, JonathanPetit commented
Le dernier commit est l'ajout du code arduino pour les capteurs ultrasons. Il y a encore un ou deux bugs dans le résultat de communication arrivé à la raspberry. Cela provient surement du code arduino. Ce sera fixer dans le courant de la semaine prochaine!

2017-02-05 17:34 UTC, charlesvdv reviewed
Juste quelques détails à modifier pour que ce soit parfait !

2017-02-05 17:34 UTC, charlesvdv commented on code/arduino/us_sensors.ino
> +const byte N_MEASURES = 5;
Utilise ```#define``` au lieu de ```const``` pour des constantes définies au dessus de ton code.

2017-02-05 17:34 UTC, charlesvdv commented on code/raspberrypi/range_sensors.py
> +        cmd = I2C.pack8(1, sensor)
Mettre les ```int``` dans des constantes pourrait être plus clair pour le lecteur.

2017-02-05 17:34 UTC, charlesvdv commented on code/raspberrypi/main.py
> +from range_sensors import RangeSensor
Pas sur que ce code devrait être merger vu qu'on utilisera d'office pas comme ça dans la version finale.

2017-02-05 17:34 UTC, charlesvdv commented on code/arduino/us_sensors.ino
> +
useless lines.

2017-02-05 21:34 UTC, azerupi commented on code/raspberrypi/range_sensors.py
> +        cmd = I2C.pack8(1, sensor)
Le mieux serait probablement d'utiliser une énumération

2017-02-05 21:36 UTC, azerupi commented on code/raspberrypi/main.py
> +from range_sensors import RangeSensor
Le main.py?
Oui, la c'est majoritairement pour pouvoir tester, mais je pense que ça peut mal de le merger. Il changera quand on ajoutera plus de code.

2017-02-05 21:44 UTC, azerupi commented on code/arduino/us_sensors.ino
> +const byte N_MEASURES = 5;
Personnellement je préfère les constantes qu'utiliser le préprocesseur. Il n'y à pas d'avantage à utiliser `#define` au lieu de `const`

2017-02-05 21:47 UTC, azerupi commented on code/arduino/us_sensors.ino
> +
Tu parles des *"blank lines"*?

2017-02-08 19:37 UTC, azerupi commented
J'ai résolu le problème qu'on avait !!

### I2C
Monsieur Marchand m'a expliqué que dans le protocole I2C, le *master* demande à écrire et lire des données sur des registres spécifique d'un *esclave*. Pour lire plusieurs bytes d'affilées on doit indiquer un registre à partir duquel on va lire, tant que le *maitre* n'envoie pas de signal d’arrêt, l'*esclave* va envoyer les registres suivants.

Donc, pour résoudre le problème qu'on avait, j'ai ajouté une variable dans l'arduino qui mémorise l'état de la réponse à la commande. Quand on reçoit une commande de la Pi, on passe dans l'état *command_processed = false* et on ignore les autres messages que la Pi envoie, jusqu'au moment ou l'arduino à pu envoyé sa réponse.

**Mais...** je ne suis pas super content de cette approche, je pense que ce serait mieux de se mettre d'accord d'ignorer tous les bytes null `0x00`. De cette façon, on ne dépends plus de l'ordre des messages. Tout byte non-null sera considéré une nouvelle commande, les bytes null seront ignorés ou considérés comme la fin d'une commande. 

Qu'en pensez-vous? 

### Commandes

Après réflexion, je me dis que les commandes choisies ici ne sont pas toutes utiles.
Depuis qu'on a ajouté la commande `get_number_of_sensors`, la commande `enumerate_sensors` n'apporte plus rien de plus. Comme les capteurs sont numérotés de 1 à nombre de capteurs + 1, cette commande renverra juste une liste consécutive...

Je propose de la supprimer.

### Abstraction arduino

J'ai quelques idées à explorer pour créer des abstractions pour le code Arduino, mais comme le code ici fonctionne déjà, je propose qu'on le merge déjà pour que tout le monde y ai accès facilement. Si je trouve un bon design je ferai un nouveau PR.

Donc je pense que ceci est prêt à être reviewed, @charlesvdv?

2017-02-09 09:01 UTC, charlesvdv requested changes

2017-02-09 09:01 UTC, charlesvdv commented on code/raspberrypi/i2c.py
> +        if num_bytes == 1:
Normalement on a plus besoin de ca vu que ```read_i2c_block_data``` devrait aussi gérer les receive d'un byte et ca permetterait aussi d'etre plus conforme avec la nouvelle facon de faire les choses c-à-d mettre 0x00 sur le bus quand on a fini la commande.

2017-02-09 09:01 UTC, charlesvdv commented on code/raspberrypi/i2c.py
> +    def __init__(self, adress):
C'est ```address``` et pas ```adress```. Il y a plusieurs endroits ou il faut le changer (dans ```us_sensors.ino``` également).

2017-02-09 09:01 UTC, charlesvdv commented on code/arduino/us_sensors.ino
> +const byte N_MEASURES = 5;
Je n'ai pas pensé que les bonnes pratiques du C sont différentes des bonnes pratiques du C++. C'est nickel alors!

2017-02-09 09:01 UTC, charlesvdv commented on code/raspberrypi/main.py
> +from range_sensors import RangeSensor
Ok pour le garder pour l'instant 😄 c'est vrai que ca ne fait pas de mal.

2017-02-09 09:01 UTC, charlesvdv commented on code/raspberrypi/range_sensors.py
> +        cmd = I2C.pack8(1, sensor)
C'est vrai que ce serait plus propre avec des [enums](https://www.python.org/dev/peps/pep-0435/). Ca serait quand meme pas mal de faire juste pour avoir une vue d'ensemble sur les commandes qu'on peut faire et directement avoir l'id de la commande.

2017-02-09 09:01 UTC, charlesvdv commented on code/arduino/us_sensors.ino
> +                Wire.write( i );
Gros gros détail mais tant qu'on y ait autant avoir la meme *convention de codage* partout. J'écrirais plutot ```Wire.write(i);```

2017-02-09 09:01 UTC, charlesvdv commented on code/arduino/us_sensors.ino
> +            Wire.write( N_SENSORS );
La meme que juste au dessus.

2017-02-09 09:10 UTC, charlesvdv commented
Un autre truc que l'on devrait ajouter sont des logs dans le code de la raspberry. J'ai oublié de mettre ca dans la review.

2017-02-09 09:14 UTC, azerupi commented
Merci! 
Je suis d'accord avec tout ce que tu as dis, je ferai les modifs tantôt.
Le logging est pas indispensable pour cette PR, il peut être ajouté par une PR ultérieurement :)

2017-02-09 15:46 UTC, azerupi commented
Ok, je pense que j'ai adressé tout ce qu'il restait. J'ai également rajouté des commentaires, surtout dans le code python et j'ai supprimé la commande qui permet d'énumérer les capteurs, vu qu'elle n'as pas vraiment d'utilité.

A priori, je n'ai pas changé grand chose, mais sachez que je n'ai pas testé ce dernier commit.

2017-02-09 16:28 UTC, JonathanPetit commented
Normalement vu ce que tu as changé cela ne doit pas poser trop de problèmes... 
Mais je serais d'avis de le tester avant de le merge?

2017-02-09 19:20 UTC, charlesvdv commented on code/raspberrypi/range_sensors.py
> +    the range-sensor mdoule.
typo avec ```module```.

2017-02-09 19:21 UTC, charlesvdv commented on code/raspberrypi/range_sensors.py
> +    The Raspberry Pi sens a byte to the module containing a command
ca serait plutot ```send``` non ?

2017-02-09 19:23 UTC, charlesvdv approved these changes

2017-02-09 19:24 UTC, charlesvdv commented
@azerupi dès que le code est tester et que tu as corrigé les 2 petites typos on pourra merger tout ca 😄

2017-02-09 20:01 UTC, azerupi commented on code/raspberrypi/range_sensors.py
> +    The Raspberry Pi sens a byte to the module containing a command
Oui, bien vu!

2017-02-10 10:38 UTC, azerupi commented
J'ai testé, résolu quelques erreurs et ça fonctionne bien.

Il y à juste un truc qui peut être amélioré, c'est que l'arduino block pendant un petit moment quand le capteur pointe dans le vide et fini par renvoyer 0 comme distance. On pourrait essayer de résoudre le problème nous même, ou alors on pourrait regarder si en utilisant la librairie [NewPing](http://playground.arduino.cc/Code/NewPing) le problème disparaît de lui même.

En attendant, le code est bon pour merger. Je ferrai des tests avec NewPing quand je testerai mes idées d'abstractions pour l'I2C du code Arduino.

2017-02-10 13:26 UTC, charlesvdv commented
Je pense que si on mets un ```timeout``` plus faible pour [pulseIn](https://www.arduino.cc/en/Reference/PulseIn) on diminuerait le problème.

2017-02-10 14:52 UTC, azerupi commented
J'ai essayé, mais ça n'avait pas l'air de changer quelque chose

2017-02-10 15:11 UTC, charlesvdv commented
Ok parfait ! Je vais merger alors ! Merci beaucoup @azerupi @JonathanPetit  pour la PR!

2017-02-10 15:12 UTC, merged